# Generated by Django 4.2.8 on 2023-12-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='User id')),
                ('description', models.TextField(max_length=250, verbose_name='Description')),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Start Price')),
                ('image_url', models.CharField(max_length=100, verbose_name='Image Url')),
                ('expiration_hours', models.PositiveSmallIntegerField(default=24)),
                ('current_applicant', models.CharField(max_length=100, verbose_name='Current Applicant')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Current Price')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
            },
        ),
    ]
