# Generated by Django 4.2.8 on 2023-12-13 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='User id')),
            ],
            options={
                'verbose_name': 'Custom user',
                'verbose_name_plural': 'Custom users',
            },
        ),
        migrations.CreateModel(
            name='UserBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bid cost')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lot.lot', verbose_name='Lot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lot.customuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'User bid',
                'verbose_name_plural': 'User bids',
                'unique_together': {('user', 'lot')},
            },
        ),
        migrations.AddField(
            model_name='lot',
            name='bidders',
            field=models.ManyToManyField(null=True, related_name='bids', through='lot.UserBid', to='lot.customuser'),
        ),
    ]
