# Generated by Django 4.2.8 on 2023-12-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0003_alter_lot_bidders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Current Price'),
        ),
    ]
