# Generated by Django 4.2.8 on 2023-12-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot', '0004_alter_lot_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='start_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Start Price'),
        ),
    ]
